---
title: "2. RStudioとGitHubの連携"
author: "kazutan"
output: html_document
---

```{r child="children/chunk_options.Rmd"}
```


## 事前の手続き
- まずはGitHubのサイトで新規リポジトリを作成してください。
- リポジトリ名は、後でRStudioで作るプロジェクト名と一致させておくとわかりやすいです
- この際.gitignoreは不要です(RStudioが自動的に作ってくれるから)
- ライセンスは選んでおいたほうが楽です
- README.mdはとりあえず作っておいてOK
- このリポジトリの「git@github.com:ほげほげ」が後から必要になります(これがリポジトリURLです)

## GitHubリポジトリとプロジェクトフォルダをつなげる
いくつかパターンがあります。

### 新規プロジェクトで新しいフォルダから作る
一番楽です。

1. 「New Project...」で新規プロジェクトを作る
2. 「Version Control」を選択
3. 「Git」を選択
4. "Repository URL:"にGitHubで作ったリポジトリURLをコピペ
5. "Project directory name:"は自動ではいります
6. "Create (ry"はいつもどおりプロジェクトのフォルダを設置する場所を指定

これでOKです。この方法の基本的な考え方は、「すでにGitHubに存在するリポジトリをLocalにクローン(フォーク? ブランチ?)して、それをRStudioでプロジェクト化してバージョン管理」です。

### 既存のプロジェクトフォルダをGitHubリポジトリにつなげる
けっこうハマりどころがおおいし面倒。

#### バージョン管理のスイッチをONにする
1. 既存のプロジェクトを開く
2. Tools→Project Options... を開く
3. Git/SVNから、"Version control system:"をGitにする
4. 「initつくるかい?(意訳)」と聞かれるので"OK"をクリック
5. その後も"OK"をクリック

これで、まずLocalでGit(バージョン管理)がスタートします。ここで、**一度RStudioを再起動**してください。再起動したら、今後はGitHubにつなぎます:

#### リモートリポジトリとつなげる
6. Tools→Shell...で、端末を開く
7. 以下のコマンドを入力

```
$ git remote add origin {リポジトリURL}
```

これは、Localのリポジトリに対して「リモート先として{リポジトリURL}を追加してくれ」という命令です。正確には違うと思いますが多分大丈夫です。このまま端末でいきます:

8. 以下のコマンドを入力
```
$ git add .
```

ローカルのリポジトリにこのプロジェクトたちのファイルを登録します。詳しくは別紙資料を。  
この後Pushしたくなりますが、実行すると(多分)弾かれます。「一度もPullしてねーけぇだめじゃ(適当意訳)」と怒られます。そこで先にリモート先のリポジトリをPullします。

9. 以下のコマンドを入力

```
$ git pull {リポジトリURL}
```

うまくpullしてmergeできるようなら、commitコメント入力を求められます。なおこの時のエディタはvimなので、vimの操作方法が求められます。別紙資料p.26参照。  
もしここでpullがエラーでうまく行かない時は、とりあえずfetchしてからrebaseやmergeを実行してください。

この作業が成功すると、LocalのプロジェクトフォルダにGitHubのリポジトリにあったLicenseやREADME.mdなどが入ってくるはずです。あとはpushしてみましょう。

10. 以下のコマンドを入力

```
$ git push
```

うまく行ったかどうか、GitHubの自分のリポジトリを確認してください。ちゃんとGitHubにまで届いていたらOKです。こで、**一度RStudioを再起動**してください。

## RStudioでのバージョン管理
上記手続きでバージョン管理をスタートさせると、一番上のメニューアイコンでGitのボタンが出ます。ここで管理していきます。

### Commitについて
編集してファイルを保存したらCommitしてください。"Stage"ってのが舞台に上げるというニュアンスでOKです。StageにチェックをいれてCommitを実行すればCommitされます。

### diffについて
差分です。どこが変わったのかをチェックできます。

### Historyについて
どんな流れなのか、そして現在のブランチやHEADなどをみることができます。

## その他
基本はGitです。一緒にGitを勉強しましょう。

以上。
