---
title: "3. forkとpull request"
author: "kazutan"
date: "2015年9月12日"
output: html_document
---

```{r child="children/chunk_options.Rmd"}
```

## githubでforkしてpull requestsまで

### まずはfork
ブラウザを開いて、事前にGithubにログインしておいてください。

1. ブラウザでforkしたいリポジトリ(のトップ)を表示
2. forkボタン(リポジトリ名のヨコの+マーク)をクリック
3. これでfork完了
4. ファイル作成のウィンドウが出ますが、とりあえずキャンセルでOKです


### ローカルに持ってくる(RStudioを利用) 

1. forkしたら、自分のリポジトリ一覧へ移動
2. (自分のアカウント名)/(forkしたリポジトリ名)のリポジトリをクリック
3. 画面右側のところにある、「HTTPS clone URL」のところからURLをコピーしておく
4. RStudioを起動
5. [File]→[new Project...]を選択
6. [Version Control]→[Git]を選択
7. [Repository URL:]には3でコピーしたURLを貼り付ける
8. すると自動的に「Project directory name:]が入るので、問題なければそのまま。
9. [Create project as subdirectory of:]はローカルディレクトリの場所です。お好みで。
10. [OK]を押すと、RStudioが自動的に**自分の**リポジトリからcloneしてRStudioのプロジェクトを作成します
11. あとは通常通りプロジェクトの開発をします


### 編集

自分が編集したいように編集してください。なおこれはバージョンコントロールが効いています。


### コミットして(自分の方のリポジトリへ)push

編集してファイルを保存します。この時点で「ローカルにcloneしてきたファイルを編集して保存した」状態になります。

この「ローカルにcloneしてきたファイルの変更」をcommitしましょう。Gitタブからcommitします。これで、「ローカルにあるリポジトリに変更がコミット」されました。これらはmyリポジトリと同一です。

次に、これを自分のremoteリポジトリ(今回の場合Githubにおいてるリポジトリ)に反映(push)しましょう。ここでさっきつまづきました。

まずはRStudioでそのまま[↑push]を押してみてください。これでエラーが出ずにうまくいけば問題なしです。でも多分エラーが出ます。初回のpushの場合、大抵エラーがでるんじゃないかなと思います。エラーが出た場合は、仕方ないのでterminalで実行します。　RStudioのメニューから[Tooles]→[Shell...]でTerminalを起動させてください。

現在のプロジェクトのディレクトリでTerminalが立ち上がるはずですので、それを確認したら以下の操作を実行してください:

```
$ git push
```

これですんなり行けばOKです。場合によってはGithubのアカウントとpassを求めてくるかと思いますので、その時は入力してください。どうもRStudio上でのPushやPullはちょいちょいうまくいかないことが多いですので、commitまではRStudio、PushあたりはTerminalでやったほうが無難ですね…

pushがうまくいったら、ブラウザで自分のリポジトリを確認してみてください。変更が反映されていればOKです。


### pull requestを出す
では自分が変更した分を、本家のリポジトリに組み入れてもらう(pull)ように、リクエスト(pull request)を出してみましょう。

まず、**自分の**Github上にあるリポジトリをブラウザで表示します。最新コミット情報の右にある「Pull request」をクリックします。すると、本家のリポジトリとforkしてきた自分のリポジトリを自動的に比較して、mergeできるかどうかを検討します。変更がぶつかってしまう場合には、ディスカッションが必要になるでしょう。

内容を確認し、リクエストを出してもいいのであれば、緑色の[Create pull request]をクリックしてください。

その後に、このpull requestのタイトルと内容を記述するウィンドウが出ますので、相手をはじめ他の人に「このpull requestはどういう内容なのか」がわかるように記述しましょう。記述したら、プルリクを投げてください。これでこちらの作業は終了です。

確認のため、**本家の**リポジトリを見に行ってください。画面右側のサイドメニューにある、[Pull request]の数字が増えてるはずです。そこをクリックすると、先ほど投げたプルリクが表示されています。